// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communicationProtocol.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class DroneMessage_Attitude;
@class DroneMessage_BaroData;
@class DroneMessage_BatteryData;
@class DroneMessage_CommandSet;
@class DroneMessage_Position;
@class DroneMessage_ThreeDimensionalData;
@class DroneMessage_Velocity;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum DroneMessage_FlightMode

typedef GPB_ENUM(DroneMessage_FlightMode) {
  DroneMessage_FlightMode_MDegraded = 0,
  DroneMessage_FlightMode_MPassThrough = 1,
  DroneMessage_FlightMode_MFlybywire = 2,
  DroneMessage_FlightMode_MAutonomous = 3,
  DroneMessage_FlightMode_MLanded = 4,
  DroneMessage_FlightMode_MxAutonomousAi = 5,
  DroneMessage_FlightMode_MxUnavailable = 6,
};

GPBEnumDescriptor *DroneMessage_FlightMode_EnumDescriptor(void);

BOOL DroneMessage_FlightMode_IsValidValue(int32_t value);

#pragma mark - CommunicationProtocolRoot

@interface CommunicationProtocolRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - DroneMessage

typedef GPB_ENUM(DroneMessage_FieldNumber) {
  DroneMessage_FieldNumber_CurrentMode = 1,
  DroneMessage_FieldNumber_CurrentSpeed = 2,
  DroneMessage_FieldNumber_CurrentPosition = 3,
  DroneMessage_FieldNumber_CurrentAttitude = 4,
  DroneMessage_FieldNumber_BmpRaw = 5,
  DroneMessage_FieldNumber_GyroRaw = 6,
  DroneMessage_FieldNumber_MagRaw = 7,
  DroneMessage_FieldNumber_AccelRaw = 8,
  DroneMessage_FieldNumber_CurrentBatteryData = 9,
  DroneMessage_FieldNumber_OutputCommandSet = 10,
  DroneMessage_FieldNumber_Waypoint = 12,
  DroneMessage_FieldNumber_HomeBase = 13,
  DroneMessage_FieldNumber_SeaLevelPressure = 14,
  DroneMessage_FieldNumber_InputCommandSet = 15,
  DroneMessage_FieldNumber_NewMode = 16,
};

@interface DroneMessage : GPBMessage

@property(nonatomic, readwrite) BOOL hasCurrentMode;
@property(nonatomic, readwrite) DroneMessage_FlightMode currentMode;

@property(nonatomic, readwrite) BOOL hasCurrentSpeed;
@property(nonatomic, readwrite, strong, null_resettable) DroneMessage_Velocity *currentSpeed;

@property(nonatomic, readwrite) BOOL hasCurrentPosition;
@property(nonatomic, readwrite, strong, null_resettable) DroneMessage_Position *currentPosition;

@property(nonatomic, readwrite) BOOL hasCurrentAttitude;
@property(nonatomic, readwrite, strong, null_resettable) DroneMessage_Attitude *currentAttitude;

@property(nonatomic, readwrite) BOOL hasBmpRaw;
@property(nonatomic, readwrite, strong, null_resettable) DroneMessage_BaroData *bmpRaw;

@property(nonatomic, readwrite) BOOL hasGyroRaw;
@property(nonatomic, readwrite, strong, null_resettable) DroneMessage_ThreeDimensionalData *gyroRaw;

@property(nonatomic, readwrite) BOOL hasMagRaw;
@property(nonatomic, readwrite, strong, null_resettable) DroneMessage_ThreeDimensionalData *magRaw;

@property(nonatomic, readwrite) BOOL hasAccelRaw;
@property(nonatomic, readwrite, strong, null_resettable) DroneMessage_ThreeDimensionalData *accelRaw;

@property(nonatomic, readwrite) BOOL hasCurrentBatteryData;
@property(nonatomic, readwrite, strong, null_resettable) DroneMessage_BatteryData *currentBatteryData;

@property(nonatomic, readwrite) BOOL hasOutputCommandSet;
@property(nonatomic, readwrite, strong, null_resettable) DroneMessage_CommandSet *outputCommandSet;

//Now the "input" messages
@property(nonatomic, readwrite) BOOL hasWaypoint;
@property(nonatomic, readwrite, strong, null_resettable) DroneMessage_Position *waypoint;

@property(nonatomic, readwrite) BOOL hasHomeBase;
@property(nonatomic, readwrite, strong, null_resettable) DroneMessage_Position *homeBase;

@property(nonatomic, readwrite) BOOL hasSeaLevelPressure;
@property(nonatomic, readwrite) float seaLevelPressure;

@property(nonatomic, readwrite) BOOL hasInputCommandSet;
@property(nonatomic, readwrite, strong, null_resettable) DroneMessage_CommandSet *inputCommandSet;

@property(nonatomic, readwrite) BOOL hasNewMode;
@property(nonatomic, readwrite) DroneMessage_FlightMode newMode;

@end

#pragma mark - DroneMessage_Position

typedef GPB_ENUM(DroneMessage_Position_FieldNumber) {
  DroneMessage_Position_FieldNumber_Timestamp = 20,
  DroneMessage_Position_FieldNumber_RealTime = 21,
  DroneMessage_Position_FieldNumber_Latitude = 22,
  DroneMessage_Position_FieldNumber_Longitude = 23,
  DroneMessage_Position_FieldNumber_Altitude = 24,
};

@interface DroneMessage_Position : GPBMessage

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t timestamp;

@property(nonatomic, readwrite) BOOL hasRealTime;
@property(nonatomic, readwrite) float realTime;

@property(nonatomic, readwrite) BOOL hasLatitude;
@property(nonatomic, readwrite) float latitude;

@property(nonatomic, readwrite) BOOL hasLongitude;
@property(nonatomic, readwrite) float longitude;

@property(nonatomic, readwrite) BOOL hasAltitude;
@property(nonatomic, readwrite) int32_t altitude;

@end

#pragma mark - DroneMessage_Velocity

typedef GPB_ENUM(DroneMessage_Velocity_FieldNumber) {
  DroneMessage_Velocity_FieldNumber_Timestamp = 30,
  DroneMessage_Velocity_FieldNumber_Speed = 31,
  DroneMessage_Velocity_FieldNumber_CourseOverGround = 32,
  DroneMessage_Velocity_FieldNumber_RateOfClimb = 33,
};

@interface DroneMessage_Velocity : GPBMessage

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t timestamp;

@property(nonatomic, readwrite) BOOL hasSpeed;
@property(nonatomic, readwrite) int32_t speed;

@property(nonatomic, readwrite) BOOL hasCourseOverGround;
@property(nonatomic, readwrite) int32_t courseOverGround;

@property(nonatomic, readwrite) BOOL hasRateOfClimb;
@property(nonatomic, readwrite) int32_t rateOfClimb;

@end

#pragma mark - DroneMessage_Attitude

typedef GPB_ENUM(DroneMessage_Attitude_FieldNumber) {
  DroneMessage_Attitude_FieldNumber_Timestamp = 40,
  DroneMessage_Attitude_FieldNumber_CourseMagnetic = 41,
  DroneMessage_Attitude_FieldNumber_Pitch = 42,
  DroneMessage_Attitude_FieldNumber_Roll = 43,
};

@interface DroneMessage_Attitude : GPBMessage

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t timestamp;

@property(nonatomic, readwrite) BOOL hasCourseMagnetic;
@property(nonatomic, readwrite) int32_t courseMagnetic;

@property(nonatomic, readwrite) BOOL hasPitch;
@property(nonatomic, readwrite) int32_t pitch;

@property(nonatomic, readwrite) BOOL hasRoll;
@property(nonatomic, readwrite) int32_t roll;

@end

#pragma mark - DroneMessage_BaroData

typedef GPB_ENUM(DroneMessage_BaroData_FieldNumber) {
  DroneMessage_BaroData_FieldNumber_Timestamp = 50,
  DroneMessage_BaroData_FieldNumber_Pressure = 51,
  DroneMessage_BaroData_FieldNumber_Temperature = 52,
};

@interface DroneMessage_BaroData : GPBMessage

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t timestamp;

@property(nonatomic, readwrite) BOOL hasPressure;
@property(nonatomic, readwrite) float pressure;

@property(nonatomic, readwrite) BOOL hasTemperature;
@property(nonatomic, readwrite) float temperature;

@end

#pragma mark - DroneMessage_ThreeDimensionalData

typedef GPB_ENUM(DroneMessage_ThreeDimensionalData_FieldNumber) {
  DroneMessage_ThreeDimensionalData_FieldNumber_Timestamp = 60,
  DroneMessage_ThreeDimensionalData_FieldNumber_X = 61,
  DroneMessage_ThreeDimensionalData_FieldNumber_Y = 62,
  DroneMessage_ThreeDimensionalData_FieldNumber_Z = 63,
};

@interface DroneMessage_ThreeDimensionalData : GPBMessage

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t timestamp;

@property(nonatomic, readwrite) BOOL hasX;
@property(nonatomic, readwrite) float x;

@property(nonatomic, readwrite) BOOL hasY;
@property(nonatomic, readwrite) float y;

@property(nonatomic, readwrite) BOOL hasZ;
@property(nonatomic, readwrite) float z;

@end

#pragma mark - DroneMessage_BatteryData

typedef GPB_ENUM(DroneMessage_BatteryData_FieldNumber) {
  DroneMessage_BatteryData_FieldNumber_Timestamp = 70,
  DroneMessage_BatteryData_FieldNumber_Voltage = 71,
  DroneMessage_BatteryData_FieldNumber_Current = 72,
  DroneMessage_BatteryData_FieldNumber_Percentage = 73,
};

@interface DroneMessage_BatteryData : GPBMessage

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t timestamp;

@property(nonatomic, readwrite) BOOL hasVoltage;
@property(nonatomic, readwrite) int32_t voltage;

@property(nonatomic, readwrite) BOOL hasCurrent;
@property(nonatomic, readwrite) int32_t current;

@property(nonatomic, readwrite) BOOL hasPercentage;
@property(nonatomic, readwrite) int32_t percentage;

@end

#pragma mark - DroneMessage_CommandSet

typedef GPB_ENUM(DroneMessage_CommandSet_FieldNumber) {
  DroneMessage_CommandSet_FieldNumber_Yaw = 80,
  DroneMessage_CommandSet_FieldNumber_Pitch = 81,
  DroneMessage_CommandSet_FieldNumber_Thrust = 82,
};

@interface DroneMessage_CommandSet : GPBMessage

@property(nonatomic, readwrite) BOOL hasYaw;
@property(nonatomic, readwrite) int32_t yaw;

@property(nonatomic, readwrite) BOOL hasPitch;
@property(nonatomic, readwrite) int32_t pitch;

@property(nonatomic, readwrite) BOOL hasThrust;
@property(nonatomic, readwrite) int32_t thrust;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
